### PR TITLE
Fix probability-B tutorial

### PR DESCRIPTION
**Pull request by UhanWu**
probability-B tutorial

### CODE REVIEW

**Comment by UhanWu** [comment]
I will Nuke from orbit, please close this pull when see.

**Comment by davidkane9** [comment]
Follow the Style Guide. Example problem:

mutate(N=as.factor(N))%>%

Also, fix the merge conflicts.

**Comment by davidkane9** [comment]
Maybe delete this PR. You should not have two open PRs for the same chapter, I think.

**Comment by UhanWu** [comment]
I don't think I can delete it, maybe just close it?

**Pull request closed without merging**
