### PR TITLE
put necessary Rmd chunks into child_documents for simpler organization

### PR DESCRIPTION
**Pull request by NuoWenLei**
Don't merge yet, idea came from community post:

https://community.rstudio.com/t/include-custom-code-chunks-from-separate-files/109216

and the link they provided:

https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

I tried it on Visualization B and it works fine, no problems in terms of submission, answers, etc. Seems that the inheriting, or replacing is done before the file actually compiles into html, so it doesn't change the functionality of the original Rmd chunks.

### CODE REVIEW

**Comment by NuoWenLei** [comment]
But then probably should check in about it before implementing, because might need to change stuff in instructions.Rmd and stuff like that

**Comment by davidkane9** [comment]
This seems like a promising approach!

**Comment by NuoWenLei** [comment]
Please pull this request now before making other commits

**Comment by NuoWenLei** [comment]
because this changes every tutorial

**Pull request merged**
