### PR TITLE
test commit for chapter 2 tutorials

### PR DESCRIPTION
**Pull request by AM-lmn**

### CODE REVIEW

**Comment by davidkane9** [comment]
Why are you changing r build ignore?

**Comment by AM-lmn** [comment]
It just happened while I tried to fork the repo to work on it, and when the project loaded I saw the the r build ignore file was changed. I followed the instructions here: https://ppbds.github.io/primer/set-up-for-working-on-the-primer.html

**Comment by AM-lmn** [comment]
Is it possible you could approve this PR then make another commit deleting line 15 of .Rbuildignore?

**Comment by davidkane9** [comment]
Fix the PR. Better yet, wait till you have a meaningful number of changes to submit a PR.

**Pull request closed without merging**
