### PR TITLE
add oauth walkthrough page and made a bunch of submission collection functions

### PR DESCRIPTION
**Pull request by NuoWenLei**

### CODE REVIEW

**Comment by NuoWenLei** [comment]
It works!

**Comment by NuoWenLei** [comment]
At least on my end

**Comment by NuoWenLei** [comment]
@davidkane9 Can you add `gmailr` and `googledrive` to DESCRIPTION? I'm scared of messing with it now

**Comment by davidkane9** [comment]
Done. You need to pr_merge_main

**Pull request merged**
