### PR TITLE
probability-b + style fix.

### PR DESCRIPTION
**Pull request by UhanWu**

### CODE REVIEW

**Comment by davidkane9** [comment]
This fails R CMD check.

Output created: tutorial.html
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (???): rendering /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpkBXkCo/file16f31180635b/primer.tutorials.Rcheck/primer.tutorials/tutorials/05-probability-B/tutorial.Rmd ──
Error: Error: '...' used in an incorrect context

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 27 ]
Error: Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 3 notes ✖
Error: Process completed with

**Comment by UhanWu** [comment]
I think the problem is with the ... like in mutate(result= ...), I change that to x and it now shows x, not sure it is a big deal.

**Comment by davidkane9** [comment]
Needs to pass r CMD check. Please fix, even if you need to delete. Don't forget to make all hints eval = FALSE

**Comment by UhanWu** [comment]
It seems like the problem is still on the hint part, I have made the ... %>% ggplot(aes(x=result)) into comment and problem solve

**Comment by davidkane9** [comment]
Did you check that it was eval = FALSE?

**Pull request merged**
