### PR TITLE
024 wrangling more plots

### PR DESCRIPTION
**Pull request by libryan261**
last one had failed RMD check even though the document runs fine

### CODE REVIEW

**Comment by NuoWenLei** [comment]
You are using a package `viridis` that is not installed for primer.tutorials. Please add `viridis` and `hrbrthemes` to the DESCRIPTION file and try committing it

**Comment by davidkane9** [comment]
Stand by

**Comment by davidkane9** [comment]
Do a pr_merge_main and try again. Should work.

D

**Comment by davidkane9** [comment]
I am just going to accept this, despite the error.

**Pull request merged**
