### PR TITLE
add test-submission.R

### PR DESCRIPTION
**Pull request by NuoWenLei**

### CODE REVIEW

**Comment by davidkane9** [comment]
Not sure what is causing the error.

**Comment by NuoWenLei** [comment]
I'll ceck if it is locally reproducible

**Comment by NuoWenLei** [comment]
error does not show up locally

**Comment by NuoWenLei** [comment]
perhaps because files did not refresh when starting the tests?

**Comment by NuoWenLei** [comment]
So I think what's happening is that `system.file("www/session_save.rds", package = "primer.tutorials")` doesn't work in tests other than testthat.R. So I'm trying to add a variable called `session_path` to testthat.R similar to `tutorial_paths` and then accessing it in test-submission.R

**Comment by NuoWenLei** [comment]
If that is actually what's happening, I'll also have to change a few things in `test-addins.R`

**Comment by NuoWenLei** [comment]
possibilities I can think of:

- sessions cannot be used in Rcheck
- the rds file is empty for some reason
- something in `get_submissions_from_learnr_session()` function is destroying everything

**Comment by NuoWenLei** [comment]
New debug message tests if the session object has the attribute `session$options$appDir`

If it does, then it can be certain that the rds file is not empty, which will actually make things more complicated because then it'll probably be something with session, environments, and stuff. And I don't want to mess with that.

**Comment by NuoWenLei** [comment]
But that doesn't make sense because if I load the session locally, I can still use `learnr:::read_request()` to read information about the session.

If that works, why doesn't this?

Also the test passes locally, so it's probably something with Github Actions. Maybe session objects work differently on Rchecks.

**Comment by NuoWenLei** [comment]
uhoh, it's a problem with the session

**Comment by NuoWenLei** [comment]
from the current tests it seems that session doesn't work well with Github Actions

**Comment by NuoWenLei** [comment]
I'll first push a version that does not use session for tests to test other parts of the functions

**Comment by NuoWenLei** [comment]
phew, finally passed check

**Pull request merged**
