### PR TITLE
Running GitHub R CMD Check

### PR DESCRIPTION
**Pull request by AnmayG**
Since only GitHub's R CMD Check is failing, I'm using this as a kind of way to continuously run the cmd checks.

Please do not close or merge this PR because I'm going to be pushing a bunch of commits into it and checking them 1 by 1.

### CODE REVIEW

**Comment by NuoWenLei** [comment]
I think I know the problem

**Comment by NuoWenLei** [comment]
DESCRIPTION file moving shiny into Imports might not have used tab and instead a string of spaces

**Comment by NuoWenLei** [comment]
could you try that?

**Comment by NuoWenLei** [comment]
nevermind, i'm dumb, that's not the problem

**Comment by AnmayG** [comment]
Yeah I'm just trying to restart renv from scratch and see if that works

**Comment by NuoWenLei** [comment]
ok, is it possible that somehow the DESCRIPTION file was not updated? because that's the only thing I could think of

**Comment by NuoWenLei** [comment]
this is the closest error case I could find

https://travis-ci.community/t/there-is-no-package-called-shiny-despite-its-in-description/9957

**Comment by NuoWenLei** [comment]
what if you try adding shiny to both suggests and imports? Could that work?

**Comment by AnmayG** [comment]
Description file looks fine, I'm rebuilding the renv packages right now but they look fine as well,

**Comment by NuoWenLei** [comment]
let's both try different stuff at the same time, hopefully get this error fixed before other PRs

**Comment by AnmayG** [comment]
Yeah sounds good. Can we talk on Discord since GitHub comments don't update that often?

**Comment by NuoWenLei** [comment]
ok

**Comment by AnmayG** [comment]
somewhat dealt with issue now

**Pull request closed without merging**
