### PR TITLE
Replaced the Kenya Section with Covid section

### PR DESCRIPTION
**Pull request by AtillaColak**
I wrote a Covid section from scratch with a completely new graph and exercises. Moreover, this new exercise section I have created contains two more exercises than the previous exercise section.

### CODE REVIEW

**Comment by davidkane9** [comment]
Data needs to be placed in, and read from, the data directory. I don't think this does (or should) work:

covid <- read_csv('owid-covid-data.csv')

**Comment by AtillaColak** [comment]
I've knitted the file and it works, since they are in the same directory: ".../Wrangling 2.3/"

**Comment by AtillaColak** [comment]
I think it only worked on my computer. Let me fix it.

**Comment by davidkane9** [comment]
You have two (similar?) PRs open. Maybe close this one? Or is it different from the other?

**Comment by AtillaColak** [comment]
Yes sorry I forgot to close this one. The other is the fixed version

**Pull request closed without merging**
