### PR TITLE
add backup local html file for Data Webscraping

### PR DESCRIPTION
**Pull request by NuoWenLei**
There are some ip restrictions for Open Secrets, so I copied the html into a local file and those who cannot load from website can load locally.

### CODE REVIEW

**Comment by NuoWenLei** [comment]
error was from data-API, code error

**Comment by NuoWenLei** [comment]
maybe I retry after that error is fixed? Or should I fix that error?

**Comment by davidkane9** [comment]
I fixed it

**Comment by NuoWenLei** [comment]
Ok thank you

**Pull request merged**
