### PR TITLE
first version of formatting add-in

### PR DESCRIPTION
**Pull request by NuoWenLei**
Tried it on tutorial 013 and it seems to work well

### CODE REVIEW

**Comment by davidkane9** [comment]
Can you fix the R CMD check error?

**Comment by NuoWenLei** [comment]
yeah it was a problem with dependencies

**Comment by NuoWenLei** [comment]
parsermd uses a bunch of other stuff, so I added those too

**Comment by davidkane9** [comment]
Now go to sleep!

**Comment by NuoWenLei** [comment]
I'll fix this check fail first!

**Pull request merged**
